<template>
    <div class="loadingio-spinner-rolling-43fqlzouhgt">
        <div class="ldio-xokoatj7z6">
            <div></div>
        </div>
    </div>
</template>

<script>
export default {

}
</script>


<style lang="scss" scoped>
@keyframes ldio-xokoatj7z6 {
    0% {
        transform: translate(-50%, -50%) rotate(0deg);
    }

    100% {
        transform: translate(-50%, -50%) rotate(360deg);
    }
}

.ldio-xokoatj7z6 div {
    position: absolute;
    width: 30px;
    height: 30px;
    border: 5px solid $accent-color;
    border-top-color: transparent;
    border-radius: 50%;
}

.ldio-xokoatj7z6 div {
    animation: ldio-xokoatj7z6 1s linear infinite;
    top: 25px;
    left: 25px
}

.loadingio-spinner-rolling-43fqlzouhgt {
    width: 50px;
    height: 50px;
    display: inline-block;
    overflow: hidden;
    background: transparent;
}

.ldio-xokoatj7z6 {
    width: 100%;
    height: 100%;
    position: relative;
    transform: translateZ(0) scale(1);
    backface-visibility: hidden;
    transform-origin: 0 0;
    /* see note above */
}

.ldio-xokoatj7z6 div {
    box-sizing: content-box;
}

/* generated by https://loading.io/ */
</style>